---
- name: Установка и настройка Vector
  hosts: clickhouse
  become: true
  vars:
    vector_install_dir: "/opt/vector"
    vector_config_template: "vector_config.j2"
    vector_arch: "x86_64" # Укажите нужную архитектуру

  tasks:
    - name: Получение последней версии Vector
      ansible.builtin.uri:
        url: "https://api.github.com/repos/vectordotdev/vector/releases/latest"
        return_content: true
      register: vector_release

    - name: Установка переменной vector_version
      ansible.builtin.set_fact:
        v_version: "{{ vector_release.json.tag_name | replace('v', '') }}"

    - name: Скачивание дистрибутива Vector
      ansible.builtin.get_url:
        url: "https://github.com/vectordotdev/vector/releases/download/v{{ v_version }}/vector-{{ v_version }}-{{ vector_arch }}-unknown-linux-gnu.tar.gz"
        dest: "/tmp/vector-{{ v_version }}-{{ vector_arch }}.tar.gz"
        mode: "0644" # Set appropriate permissions

    - name: Создание директории для установки Vector
      ansible.builtin.file:
        path: "{{ vector_install_dir }}"
        state: directory
        mode: "0755"

    - name: Распаковка дистрибутива Vector
      ansible.builtin.unarchive:
        src: "/tmp/vector-{{ v_version }}-{{ vector_arch }}.tar.gz"
        dest: "{{ vector_install_dir }}"
        remote_src: true

    - name: Проверка содержимого директории установки Vector
      ansible.builtin.command: ls -l {{ vector_install_dir }}
      register: vector_install_contents
      changed_when: false

    - name: Debug output of installation contents
      ansible.builtin.debug:
        var: vector_install_contents.stdout_lines

    - name: Установка прав на выполнение для бинарного файла Vector
      ansible.builtin.file:
        path: "{{ vector_install_dir }}/vector-{{ vector_arch }}-unknown-linux-gnu/bin/vector"
        mode: "0755"

    - name: Копирование конфигурационного файла Vector
      ansible.builtin.template:
        src: "{{ vector_config_template }}"
        dest: "{{ vector_install_dir }}/vector.toml"
        mode: "0644" # Set appropriate permissions
      notify: Restart Vector

    - name: Установка Vector
      ansible.builtin.command: "{{ vector_install_dir }}/vector-{{ vector_arch }}-unknown-linux-gnu/bin/vector --version"
      register: vector_install
      changed_when: false

  handlers:
    - name: Restart Vector
      ansible.builtin.systemd:
        name: vector
        state: restarted
